title: Chris Buckley
description: Convert any input to UTF-8 by detecting its encoding.

url: https://cmbuckley.co.uk
baseurl: /toutf8

repository: cmbuckley/toutf8
remote_theme: "cmbuckley/cmbuckley.github.io"

plugins:
  - jekyll-github-metadata
  - jekyll-remote-theme

markdown: kramdown
highlighter: rouge
